config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "static#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Cartoon Routes
  resources :cartoons


  # User Routes



  # Favorite Routes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoon.rb
class Cartoon < ApplicationRecord

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cartoons_controller.rb
class CartoonsController < ApplicationController
  def index
    @cartoons = Cartoon.all
  end

  def new
    @cartoon = Cartoon.new
  end

  def create
    @cartoon = Cartoon.new(cartoon_params)

    if @cartoon.save
      redirect_to cartoons_path
    else
      flash.now[:error] = @cartoon.errors.full_messages
      render :new
    end
  end

  private
    def cartoon_params
      params.require(:cartoon).permit(:name)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoons_helper.rb
module CartoonsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/cartoons/_cartoon.html.erb
<div class="col s4 m4 l4">
  <div class="card small grey lighten-4">
    <div class="card-content teal-text text-darken-4">
      <span class="card-title"><%= cartoon.name %></span>
      <p>Description: WIP </p>
    </div>
    <div class="card-action teal darken-4">
      <%= link_to "More Information", cartoon_path(cartoon) %>
    </div>
  </div>
</div>

app/views/cartoons/_form_errors.html.erb
<% if flash[:error] %>
  <div class="red" style="padding: 10px;">
    <ul style="margin: 0">
      <% flash[:error].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<!-- this is a comment -->

app/views/cartoons/index.html.erb
<%= render "layouts/wrapper" do %>
  <h3 class="center">Cartoons</h3>
  <div class="row">
    <%= render @cartoons %>
  </div>
<% end %>

app/views/cartoons/new.html.erb
<%= render "layouts/wrapper" do %>
  <h3 class="center teal-text text-darken-4">Create Cartoon</h3>
  <div class="container" style="margin-bottom: 20px">
    <%= render "cartoons/form_errors" %>
    <%= form_for @cartoon do |f| %>
      <div class="input-field">
        <%= f.text_field :name %>
        <%= f.label :cartoon_name %>
      </div>

      <%= f.submit "Create Cartoon", class: "btn teal darken-4" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="teal darken-4">
  <div class="container">
    <%= link_to "Home", root_path, class: "brand-logo" %>
    <ul class="right">
      <% unless user_signed_in? %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Cartoons", cartoons_path %></li>
        <li><%= link_to "Create Cartoon", new_cartoon_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: "DELETE" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_wrapper.html.erb
<div class="container white" style="padding: 10px; margin-top: 10px;">
  <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaturdayMorningCartoonCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
  </head>

  <body class="teal">
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>